import Header from "@/components/Header/Header.component";
import styles from "./home.module.css";

export const metadata = {
    title: 'To-do-list.js',
    description: 'Generated by Basile-V',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={styles.body}>
        <Header/>
        <main>{children}</main>
        </body>
        </html>
    )
}
